# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master , development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          #- '1.5'
          - '1.4.2'
          #- 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        #include:
        #  - os: windows-latest
        #    version: '1'
        #    arch: x86
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - uses: actions/checkout@v2
          - uses: julia-actions/setup-julia@v1
            with:
              version: ${{ matrix.version }}
              arch: ${{ matrix.arch }}
          - uses: actions/cache@v1
            env:
              cache-name: cache-artifacts
            with:
              path: ~/.julia/artifacts
              key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
              restore-keys: |
                ${{ runner.os }}-test-${{ env.cache-name }}-
                ${{ runner.os }}-test-
                ${{ runner.os }}-
          - uses: julia-actions/julia-buildpkg@v1
          - uses: julia-actions/julia-runtest@v1
          - uses: julia-actions/julia-processcoverage@v1
          - uses: codecov/codecov-action@v1.3.1
            with:
               token: ${{ secrets.CODECOV_TOKEN }}
               name: codecov-umbrella
